let data = [
    {
        "identificación": "653035c2c61a4a32bd272480",
        "imagen": "https://moviestack.onrender.com/static/y5szbv8zju.jpg",
        "géneros": [
            "Horror",
            "Misterio",
            "Suspenso"
        ],
        "original_language": "es",
        "Resumen": "En Francia, en 1956, un sacerdote es asesinado violentamente y la hermana Irene comienza a investigar. Una vez más, se enfrenta cara a cara con un poderoso mal.",
        "popularidad": 4160.929,
        "fecha_lanzamiento": "6/9/2023",
        "título": "La Monja II",
        "promedio de votos": 6.986,
        "conteo_de_votos": 794,
        "página de inicio": "https://www.warnerbros.com/movies/nun2",
        "ingresos": 248010000,
        "tiempo de ejecución": 110,
        "estado": "Liberado",
        "tagline": "Confiesa tus pecados.",
        "presupuesto": 38500000
    },
    {
        "identificación": "653035c2c61a4a32bd272481",
        "imagen": "https://moviestack.onrender.com/static/vlzyyn9td8.jpg",
        "géneros": [
            "Acción",
            "Drama"
        ],
        "original_language": "es",
        "descripción general": "La historia de Tim Ballard, un ex agente del gobierno de Estados Unidos que renuncia a su trabajo para dedicar su vida a rescatar a niños de los traficantes sexuales globales",
        "popularidad": 2724.044,
        "fecha_lanzamiento": "3/7/2023",
        "título": "Sonido de la libertad",
        "promedio de votos": 8.09,
        "conteo_de_votos": 764,
        "página de inicio": "https://www.soundoffreedommovie.com/",
        "ingresos": 230953510,
        "tiempo de ejecución": 131,
        "estado": "Liberado",
        "tagline": "Lucha por la luz. Silencia la oscuridad.",
        "presupuesto": 15000000
    },
    {
        "identificación": "653035c2c61a4a32bd272482",
        "imagen": "https://moviestack.onrender.com/static/nvjjd4tbnx.jpg",
        "géneros": [
            "Aventura",
            "Acción",
            "Drama"
        ],
        "original_language": "es",
        "descripción general": "La historia de realización de deseos definitiva de un jugador adolescente de Gran Turismo cuyas habilidades de juego le valieron una serie de competiciones de Nissan para convertirse en un auténtico piloto de carreras profesional",
      "popularidad": 2101.916,
        "fecha_lanzamiento": "9/8/2023",
        "título": "Gran Turismo",
        "promedio de votos": 8.058,
        "conteo_de_votos": 946,
        "página de inicio": "https://www.granturismo.movie",
        "ingresos": 114800000,
        "tiempo de ejecución": 135,
        "estado": "Liberado",
        "tagline": "De jugador a corredor.",
        "presupuesto": 60000000
    },
    {
        "identificación": "653035c2c61a4a32bd272483",
        "imagen": "https://moviestack.onrender.com/static/kp4vyfpa8b.jpg",
        "géneros": [
            "Acción",
            "Delito",
            "Suspenso"
        ],
        "original_language": "es",
        "overview": "A lo largo de muchas misiones y contra todo pronóstico, Dom Toretto y su familia han superado en inteligencia, nerviosismo y determinación a todos los enemigos que se han cruzado en su camino. Ahora, se enfrentan al oponente más letal al que se han enfrentado jamás: una amenaza aterradora que surge de las sombras del pasado, impulsada por la venganza sangrienta y que está decidida a destrozar a esta familia y destruir todo (y a todos) lo que Dom ama, para siempre.",
        "popularidad": 1073.097,
        "fecha_lanzamiento": "17/05/2023",
        "título": "X rápido",
        "promedio de votos": 7.261,
        "conteo_de_votos": 3964,
        "página de inicio": "https://fastxmovie.com",
        "ingresos": 704709660,
        "tiempo de ejecución": 142,
        "estado": "Liberado",
        "tagline": "El final del camino comienza.",
        "presupuesto": 340000000
    },
    {
        "identificación": "653035c2c61a4a32bd272486",
        "imagen": "https://moviestack.onrender.com/static/1tq4u43wwf.jpg",
        "géneros": [
            "Fantasía",
            "Comedia"
        ],
        "original_language": "es",
        "descripción general": "Una mujer y su hijo reclutan a un variopinto grupo de supuestos expertos espirituales para que les ayuden a librar su casa de ocupantes sobrenaturales.",
        "popularidad": 1011.135,
        "fecha_lanzamiento": "26/07/2023",
        "título": "Mansión embrujada",
        "promedio de votos": 6.8,
        "número de votos": 372,
        "página de inicio": "https://movies.disney.com/mansion-encantada",
        "ingresos": 113100000,
        "tiempo de ejecución": 123,
        "estado": "Liberado",
        "tagline": "El hogar está donde está el fantasma.",
        "presupuesto": 157800000
    },
    {
        "identificación": "653035c2c61a4a32bd272484",
        "imagen": "https://moviestack.onrender.com/static/4yxeyq2o1k.jpg",
        "géneros": [
            "Comedia",
            "Aventura",
            "Fantasía"
        ],
        "original_language": "es",
        "overview": "Barbie y Ken se lo pasan genial en el colorido y aparentemente perfecto mundo de Barbie Land. Sin embargo, cuando tienen la oportunidad de ir al mundo real, pronto descubren las alegrías y los peligros de vivir entre humanos",
        "popularidad": 935.058,
        "fecha_lanzamiento": "19/07/2023",
        "título": "Barbie",
        "promedio de votos": 7.254,
        "conteo_de_votos": 5296,
        "página de inicio": "https://www.barbie-themovie.com",
        "ingresos": 1434628000,
        "tiempo de ejecución": 114,
        "estado": "Liberado",
        "eslogan": "Ella lo es todo. Él es sólo Ken.",
        "presupuesto": 145000000
    },
    {
        "identificación": "653035c2c61a4a32bd272485",
        "imagen": "https://moviestack.onrender.com/static/zv15772eut.jpg",
        "géneros": [
            "Animación",
            "Comedia",
            "Familia",
            "Fantasía",
            "Romance"
        ],
        "original_language": "es",
        "visión general": "En una ciudad donde los habitantes del fuego, el agua, la tierra y el aire conviven, una joven fogosa y un chico que se deja llevar por la corriente descubrirán algo elemental: cuánto tienen en común.",
        "popularidad": 768.839,
        "fecha_lanzamiento": "14/06/2023",
        "título": "Elemental",
        "promedio de votos": 7.754,
        "conteo_de_votos": 2580,
        "página de inicio": "https://movies.disney.com/elemental",
        "ingresos": 490797988,
        "tiempo de ejecución": 102,
        "estado": "Liberado",
        "tagline": "Los opuestos reaccionan.",
        "presupuesto": 200000000
    },
    {
        "identificación": "653035c2c61a4a32bd272487",
        "imagen": "https://moviestack.onrender.com/static/2pqmfzopqq.jpg",
        "géneros": [
            "Acción",
            "Suspenso"
        ],
        "original_language": "es",
        "overview": "Ethan Hunt y su equipo del FMI se embarcan en su misión más peligrosa hasta el momento: rastrear una nueva y aterradora arma que amenaza a toda la humanidad antes de que caiga en las manos equivocadas. Con el control del futuro y el destino del mundo en juego y las fuerzas oscuras del pasado de Ethan acercándose, comienza una carrera mortal alrededor del mundo. Enfrentado a un enemigo misterioso y todopoderoso, Ethan debe considerar que nada puede importar más que su misión, ni siquiera las vidas de las personas que más le importan",
        "popularidad": 686.447,
        "fecha_lanzamiento": "8/7/2023",
        "title": "Misión: Imposible - Dead Reckoning Parte Uno",
        "promedio de votos": 7.721,
        "número de votos": 1258,
        "página de inicio": "https://www.missionimpossible.com",
        "ingresos": 567148955,
        "tiempo de ejecución": 164,
        "estado": "Liberado",
        "tagline": "Todos compartimos el mismo destino.",
        "presupuesto": 291000000
    },
    {
        "identificación": "653035c2c61a4a32bd272488",
        "imagen": "https://moviestack.onrender.com/static/p369xj1lon.jpg",
        "géneros": [
            "Animación",
            "Acción",
            "Aventura"
        ],
        "original_language": "es",
        "overview": "Después de reunirse con Gwen Stacy, el amigable Spider-Man del vecindario de Brooklyn es catapultado a través del Multiverso, donde se encuentra con la Sociedad de las Arañas, un equipo de Spider-People encargado de proteger la existencia misma del Multiverso. Pero cuando los héroes chocan sobre cómo manejar una nueva amenaza, Miles se encuentra enfrentado a los otros Spiders y debe emprender su propio camino para salvar a quienes más ama.",
        "popularidad": 544.932,
        "fecha_lanzamiento": "31/05/2023",
        "título": "Spider-Man: A través del Spider-Verse",
        "promedio de votos": 8.437,
        "conteo_de_votos": 4489,
        "página de inicio": "https://www.acrossthespiderverse.movie",
        "ingresos": 683241751,
        "tiempo de ejecución": 140,
        "estado": "Liberado",
        "eslogan": "Lo que importa es cómo llevas la mascarilla",
        "presupuesto": 100000000
    },
    {
        "identificación": "653035c2c61a4a32bd27248a",
        "imagen": "https://moviestack.onrender.com/static/tw9rw78qoq.jpg",
        "géneros": [
            "Acción",
            "Aventura",
            "Ciencia ficción"
        ],
        "original_language": "es",
        "overview": "Cuando su intento de salvar a su familia altera inadvertidamente el futuro, Barry Allen queda atrapado en una realidad en la que el General Zod ha regresado y no hay superhéroes a los que recurrir. Para salvar el mundo en el que se encuentra y regresar al futuro que conoce, la única esperanza de Barry es correr por su vida. Pero, ¿será suficiente hacer el sacrificio máximo para restablecer el universo?",
        "popularidad": 506.89,
        "fecha_lanzamiento": "13/06/2023",
        "título": "El Flash",
        "promedio de votos": 6.885,
        "conteo_de_votos": 3018,
        "página de inicio": "https://www.dc.com/theflash",
        "ingresos": 268375616,
        "tiempo de ejecución": 144,
        "estado": "Liberado",
        "tagline": "Los mundos chocan.",
        "presupuesto": 300000000
    },
    {
        "identificación": "653035c2c61a4a32bd27248b",
        "imagen": "https://moviestack.onrender.com/static/2he6f40h5q.jpg",
        "géneros": [
            "Acción",
            "Suspenso",
            "Delito"
        ],
        "original_language": "es",
        "Descripción general": "Con el precio por su cabeza en constante aumento, John Wick descubre un camino para derrotar a la Mesa Suprema. Pero antes de poder ganar su libertad, Wick debe enfrentarse a un nuevo enemigo con poderosas alianzas en todo el mundo y fuerzas que convierten a viejos amigos en enemigos",
        "popularidad": 501.243,
        "fecha_lanzamiento": "22/3/2023",
        "título": "John Wick: Capítulo 4",
        "promedio de votos": 7.812,
        "número de votos": 4698,
        "página de inicio": "https://johnwick.movie",
        "ingresos": 426978565,
        "tiempo de ejecución": 170,
        "estado": "Liberado",
        "eslogan": "No hay vuelta atrás, solo una salida.",
        "presupuesto": 90000000
    },
    {
        "identificación": "653035c2c61a4a32bd272489",
        "imagen": "https://moviestack.onrender.com/static/0r81x6xczm.jpg",
        "géneros": [
            "Animación",
            "Familia",
            "Aventura",
            "Fantasía",
            "Comedia"
        ],
        "original_language": "es",
        "overview": "Mientras trabajan bajo tierra para reparar una cañería de agua, los plomeros de Brooklyn (y hermanos) Mario y Luigi son transportados por una misteriosa tubería y deambulan hacia un nuevo mundo mágico. Pero cuando los hermanos se separan, Mario se embarca en una búsqueda épica para encontrar a Luigi.",
        "popularidad": 479.951,
        "fecha_lanzamiento": "5/4/2023",
        "título": "La película de Super Mario Bros.",
        "promedio de votos": 7.772,
        "conteo_de_votos": 6825,
        "página de inicio": "https://www.thesupermariobros.movie",
        "ingresos": 1355725263,
        "tiempo de ejecución": 93,
        "estado": "Liberado",
        "tagline": "No todos los héroes llevan capa. Algunos llevan monos.",
        "presupuesto": 100000000
    },
    {
        "identificación": "653035c2c61a4a32bd27248c",
        "imagen": "https://moviestack.onrender.com/static/sonsvqph6g.jpg",
        "géneros": [
            "Animación",
            "Comedia",
            "Acción"
        ],
        "original_language": "es",
        "overview": "Después de años de estar protegidos del mundo humano, los hermanos Tortuga se proponen ganarse el corazón de los neoyorquinos y ser aceptados como adolescentes normales a través de actos heroicos. Su nueva amiga April O'Neil los ayuda a enfrentarse a un misterioso sindicato del crimen, pero pronto se ven superados por un ejército de mutantes que se desata sobre ellos.",
        "popularidad": 438.538,
        "fecha_lanzamiento": "31/07/2023",
        "título": "Las Tortugas Ninja Adolescentes Mutantes: Caos Mutante",
        "promedio de votos": 7.341,
        "conteo_de_votos": 709,
        "página de inicio": "https://www.teenagemutantninjaturtlesmovie.com",
        "ingresos": 176700000,
        "tiempo de ejecución": 100,
        "estado": "Liberado",
        "tagline": "Los héroes no nacen. Mutan.",
        "presupuesto": 75000000
    },
    {
        "identificación": "653035c2c61a4a32bd27248d",
        "imagen": "https://moviestack.onrender.com/static/yw8zblwiln.jpg",
        "géneros": [
            "Drama",
            "Historia"
        ],
        "original_language": "es",
        "descripción general": "La historia del papel de J. Robert Oppenheimer en el desarrollo de la bomba atómica durante la Segunda Guerra Mundial.",
        "popularidad": 438.302,
        "fecha_lanzamiento": "19/07/2023",
        "título": "Oppenheimer",
        "promedio de votos": 8.257,
        "conteo_de_votos": 3833,
        "página de inicio": "http://www.oppenheimermovie.com",
        "ingresos": 933806065,
        "tiempo de ejecución": 181,
        "estado": "Liberado",
        "tagline": "El mundo cambia para siempre.",
        "presupuesto": 100000000
    },
    {
        "identificación": "653035c2c61a4a32bd27248e",
        "imagen": "https://moviestack.onrender.com/static/3fxqsoozid.jpg",
        "géneros": [
            "Aventura",
            "Familia",
            "Fantasía",
            "Romance"
        ],
        "original_language": "es",
        "overview": "La más joven de las hijas del Rey Tritón, y la más desafiante, Ariel anhela saber más sobre el mundo más allá del mar, y mientras visita la superficie, se enamora del apuesto Príncipe Eric. Como a las sirenas se les prohíbe interactuar con los humanos, Ariel hace un trato con la malvada bruja del mar, Ursula, que le da la oportunidad de experimentar la vida en la tierra, pero en última instancia pone en peligro su vida, y la corona de su padre.",
        "popularidad": 404.909,
        "fecha_lanzamiento": "18/05/2023",
        "título": "La Sirenita",
        "promedio de votos": 6.532,
        "conteo_de_votos": 2199,
        "página de inicio": "https://movies.disney.com/la-sirenita-2023",
        "ingresos": 569244557,
        "tiempo de ejecución": 135,
        "estado": "Liberado",
        "eslogan": "¡Mira y verás, algún día seré parte de tu mundo!",
        "presupuesto": 297000000,
    },
    {
        "identificación": "653035c2c61a4a32bd272519",
        "imagen": "https://moviestack.onrender.com/static/xtoqnlgiyd.jpg",
        "géneros": [
            "Horror",
            "Misterio",
            "Delito"
        ],
        "original_language": "es",
        "overview": "Obsesionado con enseñar a sus víctimas el valor de la vida, un asesino en serie sádico y trastornado secuestra a los desobedientes. Una vez capturados, deben enfrentarse a decisiones imposibles en un juego de supervivencia horrible. Las víctimas deben luchar para recuperar sus vidas o morir en el intento...",
        "popularidad": 349.772,
        "fecha_de_lanzamiento": "1/10/2004",
        "título": "Sierra",
        "promedio de votos": 7.399,
        "conteo_de_votos": 8381,
        "página de inicio": "",
        "ingresos": 103911669,
        "tiempo de ejecución": 103,
        "estado": "Liberado",
        "tagline": "Vive o muere. Haz tu elección.",
        "presupuesto": 1200000
    },
    {
        "identificación": "653035c2c61a4a32bd2724ce",
        "imagen": "https://moviestack.onrender.com/static/twkrtig0ga.jpg",
        "géneros": [
            "Ciencia ficción",
            "Aventura",
            "Acción"
        ],
        "original_language": "es",
        "descripción general": "Ambientada más de una década después de los eventos de la primera película, conozca la historia de la familia Sully (Jake, Neytiri y sus hijos), los problemas que los persiguen, los esfuerzos que hacen para mantenerse a salvo, las batallas que libran para mantenerse con vida y las tragedias que soportan.",
        "popularidad": 325.466,
        "fecha_lanzamiento": "14/12/2022",
        "title": "Avatar: El camino del agua",
        "promedio de votos": 7.652,
        "número de votos": 9878,
        "página de inicio": "https://www.avatar.com/es/peliculas/avatar-el-camino-del-agua",
        "ingresos": 2320250281,
        "tiempo de ejecución": 192,
        "estado": "Liberado",
        "tagline": "Regreso a Pandora.",
        "presupuesto": 460000000
    },
    {
        "identificación": "653035c2c61a4a32bd2724d2",
        "imagen": "https://moviestack.onrender.com/static/bcwhnfkeag.jpg",
        "géneros": [
            "Acción",
            "Aventura",
            "Ciencia ficción"
        ],
        "original_language": "es",
        "overview": "Peter Parker es desenmascarado y ya no puede separar su vida normal de los altos riesgos que implica ser un superhéroe. Cuando pide ayuda al Doctor Strange, los riesgos se vuelven aún más peligrosos, lo que lo obliga a descubrir lo que realmente significa ser Spider-Man",
        "popularidad": 206.955,
        "fecha_lanzamiento": "15/12/2021",
        "título": "Spider-Man: Sin camino a casa",
        "promedio de votos": 7.989,
        "número de votos": 18330,
        "página de inicio": "https://www.spidermannowayhome.movie",
        "ingresos": 1921847111,
        "tiempo de ejecución": 148,
        "estado": "Liberado",
        "tagline": "El Multiverso desatado.",
        "presupuesto": 200000000
    },
    {
        "identificación": "653035c2c61a4a32bd2724d1",
        "imagen": "https://moviestack.onrender.com/static/02y2vlaxe9.jpg",
        "géneros": [
            "Aventura",
            "Acción",
            "Ciencia ficción"
        ],
        "original_language": "es",
        "overview": "Mientras los Vengadores y sus aliados continúan protegiendo al mundo de amenazas demasiado grandes para que un solo héroe pueda manejarlas, un nuevo peligro ha surgido de las sombras cósmicas: Thanos. Un déspota de infamia intergaláctica, su objetivo es recolectar las seis Gemas del Infinito, artefactos de poder inimaginable, y usarlas para infligir su retorcida voluntad en toda la realidad. Todo por lo que han luchado los Vengadores los ha llevado a este momento: el destino de la Tierra y la existencia misma nunca ha sido más incierto",
        "popularidad": 191.328,
        "fecha_lanzamiento": "25/04/2018",
        "título": "Vengadores: Infinity War",
        "promedio de votos": 8.254,
        "conteo_de_votos": 27754,
        "página de inicio": "https://www.marvel.com/movies/avengers-infinity-war",
        "ingresos": 2052415039,
        "tiempo de ejecución": 149,
        "estado": "Liberado",
        "tagline": "Un universo entero. De una vez por todas.",
        "presupuesto": 300000000
    },
    {
        "identificación": "653035c2c61a4a32bd272534",
        "imagen": "https://moviestack.onrender.com/static/p6ydaicfpp.jpg",
        "géneros": [
            "Animación",
            "Familia",
            "Aventura",
            "Comedia"
        ],
        "original_language": "es",
        "descripción general": "Ryder y los cachorros son llamados a Adventure City para evitar que el alcalde Humdinger convierta la bulliciosa metrópolis en un estado de caos",
        "popularidad": 166.862,
        "fecha_lanzamiento": "9/8/2021",
        "título": "Patrulla Canina: La Película",
        "promedio de votos": 7.426,
        "número de votos": 1150,
        "página de inicio": "https://www.pawpatrol.movie",
        "ingresos": 144327371,
        "tiempo de ejecución": 86,
        "estado": "Liberado",
        "eslogan": "Nuestro destino está en sus garras.",
        "presupuesto": 26000000
    },
    {
        "identificación": "653035c2c61a4a32bd2724d4",
        "imagen": "https://moviestack.onrender.com/static/4vz97op5y2.jpg",
        "géneros": [
            "Aventura",
            "Drama",
            "Familia"
        ],
        "original_language": "es",
        "overview": "Simba idolatra a su padre, el rey Mufasa, y se toma muy en serio su propio destino real. Pero no todos en el reino celebran la llegada del nuevo cachorro. Scar, el hermano de Mufasa y ex heredero al trono, tiene sus propios planes. La batalla por Pride Rock está plagada de traición, tragedia y drama, lo que finalmente resulta en el exilio de Simba. Con la ayuda de un par de curiosos nuevos amigos, Simba tendrá que descubrir cómo crecer y recuperar lo que es legítimamente suyo.",
        "popularidad": 164.763,
        "fecha_lanzamiento": "12/7/2019",
        "título": "El Rey León",
        "promedio de votos": 7.1,
        "conteo_de_votos": 9337,
        "página de inicio": "https://movies.disney.com/el-rey-leon-2019",
        "ingresos": 1663075401,
        "tiempo de ejecución": 118,
        "estado": "Liberado",
        "tagline": "El Rey ha regresado.",
        "presupuesto": 260000000
    },
    {
        "identificación": "653035c2c61a4a32bd2724d6",
        "imagen": "https://moviestack.onrender.com/static/0ti8kfd1n8.jpg",
        "géneros": [
            "Acción",
            "Drama"
        ],
        "original_language": "es",
        "descripción general": "Después de más de treinta años de servicio como uno de los mejores aviadores de la Marina, y esquivando el avance de rango que lo dejaría en el suelo, Pete Maverick Mitchell se encuentra entrenando a un destacamento de graduados de TOP GUN para una misión especializada como ningún piloto vivo ha visto jamás.",
        "popularidad": 159.783,
        "fecha_lanzamiento": "24/05/2022",
        "título": "Top Gun: Maverick",
        "promedio de votos": 8.3,
        "conteo_de_votos": 7582,
        "página de inicio": "https://www.topgunmovie.com",
        "ingresos": 1488732821,
        "tiempo de ejecución": 131,
        "estado": "Liberado",
        "tagline": "Siente la necesidad... La necesidad de velocidad.",
        "presupuesto": 170000000
    },
    {
        "identificación": "653035c2c61a4a32bd27252a",
        "imagen": "https://moviestack.onrender.com/static/6ha37rbtaa.jpg",
        "géneros": [
            "Aventura",
            "Fantasía"
        ],
        "original_language": "es",
        "overview": "Cuando el nombre de Harry Potter emerge del Cáliz de Fuego, se convierte en un competidor en una agotadora batalla por la gloria entre tres escuelas de magia: el Torneo de los Tres Magos. Pero como Harry nunca presentó su nombre para el Torneo, ¿quién lo hizo? Ahora Harry debe enfrentarse a un dragón mortal, feroces demonios acuáticos y un laberinto encantado, solo para encontrarse en las crueles garras de Aquel Que No Debe Ser Nombrado.",
        "popularidad": 136.279,
        "fecha_lanzamiento": "16/11/2005",
        "título": "Harry Potter y el cáliz de fuego",
        "promedio de votos": 7.816,
        "conteo_de_votos": 19322,
        "página de inicio": "https://www.warnerbros.com/movies/harry-potter-and-goblet-fire/",
        "ingresos": 895921036,
        "tiempo de ejecución": 157,
        "estado": "Liberado",
        "tagline": "Se avecinan tiempos oscuros y difíciles.",
        "presupuesto": 150000000
    },
    {
        "identificación": "653035c2c61a4a32bd2724e8",
        "imagen": "https://moviestack.onrender.com/static/piihneq9w7.jpg",
        "géneros": [
            "Acción",
            "Aventura"
        ],
        "original_language": "es",
        "descripción general": "Nathan Drake, un joven astuto de la calle, y su ocurrente compañero Victor Sully Sullivan se embarcan en una peligrosa búsqueda del 'mayor tesoro jamás encontrado'   mientras también siguen pistas que pueden llevar al hermano perdido de Nathan.",
        "popularidad": 132.586,
        "fecha_lanzamiento": "10/02/2022",
        "título": "Inexplorado",
        "promedio de votos": 7.001,
        "número de votos": 5084,
        "página de inicio": "https://www.unchartedmovie.com",
        "ingresos": 407141258,
        "tiempo de ejecución": 116,
        "estado": "Liberado",
        "tagline": "La fortuna favorece a los audaces.",
        "presupuesto": 120000000
    },
    {
        "identificación": "653035c2c61a4a32bd27251f",
        "imagen": "https://moviestack.onrender.com/static/hcd63galul.jpg",
        "géneros": [
            "Misterio",
            "Suspenso",
            "Delito"
        ],
        "original_language": "es",
        "Resumen": "El famoso detective Hércules Poirot, ahora retirado y viviendo en un exilio autoimpuesto en Venecia, asiste a regañadientes a una sesión espiritista de Halloween en un palacio embrujado y en ruinas. Cuando uno de los invitados es asesinado, el detective se ve inmerso en un mundo siniestro de sombras y secretos",
        "popularidad": 122.698,
        "fecha_lanzamiento": "13/09/2023",
        "title": "Una aparición en Venecia",
        "promedio de votos": 6.776,
        "número de votos": 586,
        "página de inicio": "https://www.20thcenturystudios.com/movies/a-haunting-in-venice",
        "ingresos": 102800000,
        "tiempo de ejecución": 104,
        "estado": "Liberado",
        "tagline": "La muerte fue sólo el comienzo.",
        "presupuesto": 60000000
    },
    {
        "identificación": "653035c2c61a4a32bd2724ed",
        "imagen": "https://moviestack.onrender.com/static/9axle2d4wj.jpg",
        "géneros": [
            "Drama",
            "Delito"
        ],
        "original_language": "es",
        "Overview": "Abarcando los años 1945 a 1955, una crónica de la familia criminal italoamericana ficticia Corleone. Cuando el patriarca de la familia del crimen organizado, Vito Corleone, apenas sobrevive a un intento de asesinato, su hijo menor, Michael, interviene para encargarse de los posibles asesinos y lanza una campaña de sangrienta venganza.",
        "popularidad": 119.011,
        "fecha_lanzamiento": "14/3/1972",
        "título": "El Padrino",
        "promedio de votos": 8.708,
        "número de votos": 18732,
        "página de inicio": "http://www.elpadrino.com/",
        "ingresos": 245066411,
        "tiempo de ejecución": 175,
        "estado": "Liberado",
        "tagline": "Una oferta que no puedes rechazar.",
        "presupuesto": 6000000
    },
    {
        "identificación": "653035c2c61a4a32bd272527",
        "imagen": "https://moviestack.onrender.com/static/4wqr6g4a28.jpg",
        "géneros": [
            "Animación",
            "Comedia",
            "Familia"
        ],
        "original_language": "es",
        "overview": "El adorable Sulley y su ocurrente compañero Mike Wazowski son el mejor equipo de terror de Monsters, Inc., la fábrica de procesamiento de gritos en Monstruópolis. Cuando una niña llamada Boo deambula por su mundo, son los monstruos los que se asustan muchísimo, y Sulley y Mike deben mantenerla fuera de la vista y hacerla volver a casa.",
        "popularidad": 115.278,
        "fecha_de_lanzamiento": "1/11/2001",
        "título": "Monstruos, S.A.",
        "promedio de votos": 7.8,
        "conteo_de_votos": 17215,
        "página de inicio": "http://movies.disney.com/monsters-inc",
        "ingresos": 579707738,
        "tiempo de ejecución": 92,
        "estado": "Liberado",
        "eslogan": "Asustamos porque nos preocupamos.",
        "presupuesto": 115000000
    },
    {
        "identificación": "653035c2c61a4a32bd2724cf",
        "imagen": "https://moviestack.onrender.com/static/6xefycbew8.jpg",
        "géneros": [
            "Drama",
            "Romance"
        ],
        "original_language": "es",
        "overview": "Rose DeWitt Bukater, de 101 años, cuenta la historia de su vida a bordo del Titanic, 84 años después. Una joven Rose sube al barco con su madre y su prometido. Mientras tanto, Jack Dawson y Fabrizio De Rossi ganan billetes de tercera clase a bordo del barco. Rose cuenta toda la historia desde la partida del Titanic hasta su muerte, en su primer y último viaje, el 15 de abril de 1912.",
        "popularidad": 113.689,
        "fecha_lanzamiento": "18/11/1997",
        "título": "Titanic",
        "promedio de votos": 7.9,
        "conteo_de_votos": 23675,
        "página de inicio": "https://www.paramountmovies.com/movies/titanic",
        "ingresos": 2264162353,
        "tiempo de ejecución": 194,
        "estado": "Liberado",
        "eslogan": "Nada en la Tierra podría interponerse entre ellos.",
        "presupuesto": 200000000
    },
    {
        "identificación": "653035c2c61a4a32bd2724eb",
        "imagen": "https://moviestack.onrender.com/static/hhl2nc1bz5.jpg",
        "géneros": [
            "Ciencia ficción",
            "Aventura"
        ],
        "original_language": "es",
        "Overview": "Paul Atreides, un joven brillante y talentoso nacido con un gran destino más allá de su comprensión, debe viajar al planeta más peligroso del universo para asegurar el futuro de su familia y su gente. Mientras fuerzas malévolas estallan en un conflicto por el suministro exclusivo del planeta del recurso más preciado que existe -un producto capaz de liberar el mayor potencial de la humanidad- sólo aquellos que puedan superar su miedo sobrevivirán.",
        "popularidad": 112.418,
        "fecha_lanzamiento": "15/09/2021",
        "título": "Duna",
        "promedio de votos": 7.789,
        "conteo_de_votos": 9455,
        "página de inicio": "https://www.dunemovie.com/",
        "ingresos": 402027830,
        "tiempo de ejecución": 155,
        "estado": "Liberado",
        "tagline": "Empieza.",
        "presupuesto": 165000000
    },
    {
        "identificación": "653035c2c61a4a32bd2724d5",
        "imagen": "https://moviestack.onrender.com/static/151vjyzxs8.jpg",
        "géneros": [
            "Ciencia ficción",
            "Acción",
            "Aventura"
        ],
        "original_language": "es",
        "Descripción general": "Cuando surge un enemigo inesperado que amenaza la seguridad mundial, Nick Fury, director de la agencia internacional de mantenimiento de la paz conocida como SHIELD, se ve en la necesidad de formar un equipo para salvar al mundo del borde del desastre. ¡Comienza un audaz esfuerzo de reclutamiento por todo el planeta!",
        "popularidad": 109.201,
        "fecha_lanzamiento": "25/04/2012",
        "título": "Los Vengadores",
        "promedio de votos": 7.71,
        "conteo_de_votos": 29199,
        "página de inicio": "https://www.marvel.com/movies/the-avengers",
        "ingresos": 1518815515,
        "tiempo de ejecución": 143,
        "estado": "Liberado",
        "tagline": "Se requiere algo de ensamblaje.",
        "presupuesto": 220000000
    }
]
